### findAllEmployees:
GET http://localhost:8080/api/employees

### findEmployeeById:
GET http://localhost:8080/api/employees/2

### addEmployee:
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "firstName": "An",
  "lastName": "Nader",
  "email": "ann@gmail.com"
}

### updateEmployeeById:
PUT http://localhost:8080/api/employees/100
Content-Type: application/json

{
  "firstName": "Amin",
  "lastName": "Amini",
  "email": "amin@gmail.com"
}

### deleteEmployeeById:
DELETE http://localhost:8080/api/employees/13
